language: go
go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
sudo: false
before_install:
  - go get -u golang.org/x/lint/golint
script:
  - test -z "`gofmt -l .`"
  - test -z "`golint ./...`"
  - go test -cover -race ./...
