language: go
go:
  - 1.18.x
  - 1.19.x
  - 1.20.x
sudo: false
before_install:
  - go install golang.org/x/lint/golint
script:
  - test -z "`gofmt -l .`"
  - test -z "`golint ./...`"
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
