language: go
go:
  - 1.18.x
  - 1.19.x
  - 1.20.x
sudo: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
