## test09
hostport: ssh.example.com:22
user_id: me
client_key_file: testfiles/test_pwd_key
client_key_pwd: my_favorite_password
datasources:
  valid: 
    driver_name: test_driver
    dsn: valid_dsn_string