## test13
- hostport: ssh.example.com:22
  user_id: me
  client_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS
    1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQB98RdfbLOuKmtf874FnMEuVJhPF5c
    r8NdVV+4U4oeA42OgIb0SfnTTpmAVjE64MWsT96hRrb9ZTzDbk/7W5NGKNEAO+usYZ1X2f
    /E/a86vG11lZRx9HZXuVccJJCzqQlX0UQMzdYtk4pGuQojGXkei+WGpLfFBIVpjKZ+0A6g
    VKJ+2ogAAAEQagV3GWoFdxkAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ
    AAAIUEAffEXX2yzriprX/O+BZzBLlSYTxeXK/DXVVfuFOKHgONjoCG9En5006ZgFYxOuDF
    rE/eoUa2/WU8w25P+1uTRijRADvrrGGdV9n/xP2vOrxtdZWUcfR2V7lXHCSQs6kJV9FEDM
    3WLZOKRrkKIxl5HovlhqS3xQSFaYymftAOoFSiftqIAAAAQgCuV4B+Cak9BWL3vLW1Knb0
    R69k2oaTNn8ipqaI/X9MNbKwFb+O5a51nhRFsCzP3pd2awmGdx7hPkXH10YnlRDrvAAAAA
    1qY290ZUBKRkMtU01HAQIDBAU=
    -----END OPENSSH PRIVATE KEY-----
  server_public_key: ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADFn9ObPW0aJ0knG1N28PhG4D6pZchQu1tSOxJ2u30sSWWtPR2FtudM4m17MxeP2+P3bxgCMVLgD+QZIEmG2H7y7gB9GBEbrgN43zGiDHEseLyqwZ7eVSlfdsEoZIqSfqnw8wLUhlwMLyBUpQG8pBG6IMIMfMAoNQGIujGcv7TuT1V4T jcote@JFC-SMG
  dsn_list:
    - valid_dsn_string